"""Omega FX v2 core package."""

from .config import (
    DEFAULT_COSTS,
    DEFAULT_CHALLENGE,
    DEFAULT_SESSION,
    DEFAULT_MR_SIGNAL_CONFIG,
    DEFAULT_STRATEGY,
    DEFAULT_SIGNAL_CONFIG,
    DEFAULT_PROFILE_BREAKOUT_V1,
    DEFAULT_PROFILE_XAU_MR_V1,
    DEFAULT_PROFILE_USDJPY_MR_V1,
    DEFAULT_PROFILE_USDJPY_MR_M15_V1,
    DEFAULT_PORTFOLIO_USDJPY_MR,
    DEFAULT_PROFILE_EURUSD_MR_M15_V1,
    DEFAULT_PROFILE_GBPUSD_MR_M15_V1,
    DEFAULT_PROFILE_XAUUSD_MR_M15_V1,
    DEFAULT_PROFILE_USDJPY_TREND_M15_V1,
    DEFAULT_PORTFOLIO_USDJPY_V2,
    DEFAULT_PORTFOLIO_M15_MR_MULTI,
    ChallengeProfile,
    InstrumentSpec,
    MeanReversionSignalConfig,
    TrendContinuationSignalConfig,
    SignalConfig,
    StrategyConfig,
    PortfolioProfile,
    StrategyProfile,
    TradingCosts,
    TradingSession,
    XAUUSD_SPEC,
)
from .data import fetch_ohlc, fetch_symbol_ohlc, fetch_xauusd_ohlc
from .signals import (
    build_atr_filter,
    build_mean_reversion_signals,
    build_signals,
    build_session_mask,
    compute_h4_sma_filter,
    compute_atr,
    generate_breakout_signals,
)
from .strategy import PlannedTrade, plan_single_trade
from .mt5_adapter import Mt5BrokerAdapter, Mt5ConnectionConfig
from .sim import (
    EvaluationBatchResult,
    EvaluationResult,
    TradeOutcome,
    run_randomized_evaluations,
    run_randomized_signal_evaluations,
    run_signal_driven_evaluation,
    run_sequential_evaluation,
    simulate_trade_path,
)
from .profile_summary import run_profile_summary
from .portfolio_summary import run_portfolio_summary
from .runtime_live import LiveRunResult, LiveTrade, run_offline_live_simulation
from .runtime_loop import BrokerAdapter, DummyBrokerAdapter, LiveRuntimeState, run_live_runtime
from .logger import get_logger

__all__ = [
    "StrategyConfig",
    "TradingCosts",
    "ChallengeProfile",
    "TradingSession",
    "InstrumentSpec",
    "DEFAULT_STRATEGY",
    "DEFAULT_COSTS",
    "DEFAULT_CHALLENGE",
    "DEFAULT_SESSION",
    "DEFAULT_MR_SIGNAL_CONFIG",
    "DEFAULT_SIGNAL_CONFIG",
    "DEFAULT_PROFILE_BREAKOUT_V1",
    "DEFAULT_PROFILE_XAU_MR_V1",
    "DEFAULT_PROFILE_USDJPY_MR_V1",
    "DEFAULT_PROFILE_USDJPY_MR_M15_V1",
    "DEFAULT_PORTFOLIO_USDJPY_MR",
    "DEFAULT_PROFILE_EURUSD_MR_M15_V1",
    "DEFAULT_PROFILE_GBPUSD_MR_M15_V1",
    "DEFAULT_PROFILE_XAUUSD_MR_M15_V1",
    "DEFAULT_PROFILE_USDJPY_TREND_M15_V1",
    "DEFAULT_PORTFOLIO_USDJPY_V2",
    "DEFAULT_PORTFOLIO_M15_MR_MULTI",
    "XAUUSD_SPEC",
    "MeanReversionSignalConfig",
    "TrendContinuationSignalConfig",
    "SignalConfig",
    "StrategyProfile",
    "PortfolioProfile",
    "build_atr_filter",
    "build_mean_reversion_signals",
    "build_signals",
    "build_session_mask",
    "compute_h4_sma_filter",
    "compute_atr",
    "generate_breakout_signals",
    "Mt5BrokerAdapter",
    "Mt5ConnectionConfig",
    "run_profile_summary",
    "run_portfolio_summary",
    "fetch_ohlc",
    "fetch_symbol_ohlc",
    "fetch_xauusd_ohlc",
    "PlannedTrade",
    "plan_single_trade",
    "TradeOutcome",
    "simulate_trade_path",
    "run_sequential_evaluation",
    "run_signal_driven_evaluation",
    "EvaluationResult",
    "run_randomized_evaluations",
    "run_randomized_signal_evaluations",
    "EvaluationBatchResult",
]
